# Generated by Django 5.2.6 on 2025-09-20 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClothItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("image_url", models.URLField()),
                ("colors_available", models.TextField()),
                ("like_count", models.IntegerField(default=0)),
                ("dislike_count", models.IntegerField(default=0)),
            ],
        ),
    ]
