# Generated by Django 5.2.6 on 2025-09-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="swiped_items",
            field=models.JSONField(default=list),
        ),
    ]
